### PR TITLE
Ability to set custom keys

### PR DESCRIPTION
**Pull request by ChristopheCVB**
Usage :
!set-{key} {value}
!{key}

### CODE REVIEW

**Comment by Cristy94** [comment]
Thanks for the PR!

One problem that I saw (looking through the code) is that you can't set links as you could for the repo directory. The problem with links is that if you type something like '!set-repo http://test.com` , the link will be converted automatically to an `a` tag by the chat and you won't be able to get back the value correctly. So, the only drawback is that when the user will try to get the repo they will see `test.com` instead of a clickable link. :)

**Comment by ChristopheCVB** [comment]
Updated !
It's working now ;)

**Comment by Cristy94** [comment]
When I try to run your bot in my stream chat I get this error: `Uncaught SyntaxError: Unexpected token u`
I don't know what breaks it :(

**Comment by ChristopheCVB** [comment]
I don't know why... It's working like a charm when I try it...

Did you copied the entire file from here : https://raw.githubusercontent.com/ChristopheCVB/livecoding-chat-bot/patch-1/chatBot.js ?

**Comment by Cristy94** [comment]
Yes, that error still appears. I am using Google Chrome 44.

Here is a screenshot: http://i.snag.gy/WE2wM.jpg
This error does not appear if I paste my chatBot.js code.

**Comment by ChristopheCVB** [comment]
Got it. The error was only on Chrome for Windows I think...

**Pull request merged**
